export const ACHIEVEMENT_STATUS = {
  INACTIVE: 'inactive',
  ACTIVATED: 'activated',
  COMPLETE: 'complete',
}

export const ACHIEVEMENT_TYPE = {
  PROGRESSIVE: 'progressive',
  EXPLORATION: 'exploration',
  TIME_BASED: 'time-based',
  SKILL_BASED: 'skill-based',
  SOCIAL: 'social',
  COLLECTION: 'collection',
  STORYLINE: 'storyline',
  EVENT: 'event',
  HIDDEN: 'hidden',
  LIFETIME: 'lifetime',
}

//mock generation food: inactive, activated, complete
//for achievement: progressive, exploration, time-based, skill-based, social, collection, storyline, event,hidden, lifetime

export const ACHIEVEMENT_SORT_BY = {
  NEWEST_FIRST: 'newest',
  OLDEST_FIRST: 'oldest',
  ASCENDING: 'a-z',
  DESCENDING: 'z-a',
}

export const WORD_SUBSECTION = {
  INTRO_1: 'intro_1',
  INTRO_2: 'intro_2',
  INTRO_3: 'intro_3',
  INTRO_4: 'intro_4',
  INTRO_5: 'intro_5',
  INTRO_6: 'intro_6',
  INTRO_7: 'intro_7',
  G_1: 'g_1',
  G_2: 'g_2',
  I_1: 'i_1',
  J_1: 'j_1',
  J_2: 'j_2',
  J_3: 'j_3',
  J_4: 'j_4',
  J_5: 'j_5',
  K_1: 'k_1',
  L_1: 'l_1',
  L_2: 'l_2',
  L_3: 'l_3',
  M_1: 'm_1',
  N_1: 'n_1',
  NYP_1: 'nyp_1',
  OSP_1: 'osp_1',
  OSP_2: 'osp_2',
  OSP_3: 'osp_3',
  S_1: 's_1',
  S_2: 's_2',
  S_3: 's_3',
  S_4: 's_4',
  SPR_1: 'spr_1',
  SPR_2: 'spr_2',
  SPR_3: 'spr_3',
  V_1: 'v_1',
  V_2: 'v_2',
  V_3: 'v_3',
  V_4: 'v_4',
  VINKEL: 'vinkel_1',
}

export const WORD_SUBGROUP = {
  ACCUMULATION: 'accumulation',
  ACTIVE_BACKING: 'activebacking',
  ACTIVITY: 'activity',
  AFFINITY: 'affinity',
  AID: 'aid',
  A_OBJ_PIECE: 'aobjectpiece',
  A_PART: 'apart',
  APPLY_CONSEPTS: 'applyConsepts',
  ART: 'art',
  A_SWORD_IN_ACTION: 'aswordinaction',
  ATTENTION: 'attention',
  BALANCE: 'balance',
  BARE_FEELING: 'barefeeling',
  BASIS: 'basis',
  BITOFCAKE: 'bitofcake',
  BLANK_CANVAS: 'blankcanvas',
  BLOW: 'blow',
  BOUNDS: 'bounds',
  BURDEN: 'burden',
  CALM: 'calm',
  CEASARS_HAND: 'ceasarshand',
  CERTAIN: 'certain',
  CHANGABLE_SPACE: 'changableSpace',
  COCKY: 'cocky',
  COMPARE: 'compare',
  COMPASS: 'compass',
  COMPENSATE: 'compensate',
  CONNECTION: 'connection',
  CONSEPTUAL_BOUNDS: 'conseptualbounds',
  CONSEPTUAL_WIDTH: 'conseptualwidth',
  CONSUMPTIN: 'consumption',
  CONTINOUS: 'continous',
  COORDINATES: 'coordinates',
  COUNT_COMPLETED: 'countcompleted',
  COUNTING: 'counting',
  CREATIONAL_REACTION: 'creationalreaction',
  CROUCH_LEGGED: 'crouchleged',
  CYLINDER: 'cylinder',
  DAD: 'dad',
  DIRECT: 'direct',
  DIMENTION_4_SPACE: 'dimention4space',
  DISCIPLINARY: 'disciplinary',
  DON_KRUGER_EFFECT: 'donkrugereffect',
  EARS: 'ears',
  EARTHBOSOM: 'earthbosom',
  ENCLOSURE: 'enclosure',
  EUCLIDEAN_SPACE: 'euclideanspace',
  EXHAUSTIBLE: 'exhaustible',
  EXPECTATIONS: 'expectations',
  EXPLAIN_THIS: 'explainthis',
  EYES: 'eyes',
  FAMILY_LIFE: 'familylife',
  FELLOWSHIP: 'fellowship',
  FIRM: 'firm',
  FORMATING: 'formating',
  FROM_AN_ANGLE: 'fromanangle',
  GAP_FORM: 'gapform',
  GLUE: 'glue',
  GOD: 'god',
  GOES_ROUND: 'goesround',
  GUARANTEED_ASSESMENT: 'guaranteedassesment',
  GUARD: 'guard',
  HEART_OF_QUESTION: 'heartofquestion',
  HEAVY_MOVEMENT: 'heavymovement',
  HIGH_PRESSURE: 'highpressure',
  HOLD_MOVEMENT: 'holdmovement',
  HOME: 'home',
  HOOK: 'hook',
  HORIZONTAL_LEVEL: 'horizontallevel',
  HORN: 'horn',
  HOW: 'how',
  ILLUSTRATIVE: 'illustrative',
  IMMITATE_ACTION: 'immitateaction',
  IMMITATE_CONCEPT: 'immitateconcept',
  IMMITATE_OBJECT: 'immitateobject',
  IMPORTANCE: 'importance',
  INDICATIVE_ORIENTATION: 'indicativeorientation',
  INDIVIDUALL: 'individuall',
  INEVITABLE: 'inevitable',
  INFO: 'info',
  INJECT: 'inject',
  INSIDE: 'inside',
  INSOLENT: 'insolent',
  INTERACTIVE: 'interactive',
  INTERPRET_gUIDANCE: 'interpretguidance',
  JAW: 'jaw',
  LEGS: 'legs',
  LIFE: 'life',
  LIFELESS: 'lifeless',
  LIFE_WONDERS: 'lifewonders',
  LINE: 'line',
  LOGIC: 'logic',
  MAN_ON_A_MISSION: 'manonamission',
  MAN_WITH_PURPOSE: 'manwithpurpose',
  MATERIAL: 'material',
  MEANING: 'meaning',
  MEATHOD_TO_MEASSURE: 'methodtomeassure',
  MOLDABLE: 'moldable',
  MONSTER: 'monster',
  MOOD: 'mood',
  MOVEMENT_TEORETICAL: 'movementteoretical',
  MOVE_STATE: 'movestate',
  MULTIPLE_DOTS: 'multipledots',
  MULTI_THREATS: 'multithreats',
  NO_IDIOTS_ALLOWED: 'noidiotsallowed',
  NONSENSE: 'nonsense',
  NONSTABLE_STATE: 'nonstablestate',
  NOT_VICTIM: 'notvictim',
  OBJECTIVE_DIRECTION: 'objectivedirection',
  OBJECTS: 'objects',
  OBJECT_WIDTH: 'objectwidth',
  OCCATIONAL: 'occational',
  OCCUPIED: 'occupied',
  OFFER: 'offer',
  OPTIONS: 'options',
  PAIN: 'pain',
  PARTITION: 'partition',
  PERSONAL_LIFE: 'personallife',
  PERSONAL_SITUATION: 'personalsituation',
  PHYSICAL_DIRECTION: 'physicaldirection',
  PICTURE: 'picture',
  PIPE: 'pipe',
  POSSESS: 'possess',
  PRACTICAL: 'practical',
  PRIMITIVE_EXPRESSION: 'primiitiveexpression',
  PRIMITIVE_LIFE_FORM: 'primitivelifeform',
  PROJECT: 'purpose',
  REACTION: 'reaction',
  REFER_TO: 'referto',
  RELATION: 'relation',
  RELEASE: 'release',
  REMEMBER: 'remember',
  RESPECT: 'respect',
  RESPONSIBLE: 'responsible',
  SCARY: 'scary',
  SEARCH: 'search',
  SEIZE: 'seize',
  SELECT: 'select',
  SELECT_ACTION: 'selectaction',
  SERVICEAID: 'serviceaid',
  SMILE: 'smile',
  SNAKE_TONGUE: 'snaketongue',
  SOUR_SITUATION: 'soursituation',
  SPEACH: 'speach',
  SPECIAL_NEED: 'specialneed',
  STABLE: 'stable',
  STABLE_STATE: 'stablestate',
  STACKABLE: 'stackable',
  STATUS: 'status',
  STICK: 'stick',
  STINGY: 'stingy',
  STRRADDLE_LEGGED: 'straddlelegged',
  STREAM_CARRYING_MOSES: 'streamcarryingmoses',
  STRING: 'string',
  STRUCTURE: 'structure',
  STUDY_PARTS: 'studyparts',
  SUPPORT: 'support',
  SWORD_CONDITION: 'swordcondition',
  SWORD_IN_SOCIETY: 'swordinsociety',
  SWORD_SPIRIT: 'swordspirit',
  SYMBOLIC_SIGNS: 'symbolicSigns',
  TAPE: 'tabe',
  TASTE: 'taste',
  TECHNOLOGY_CONSEPTION: 'technologyconseption',
  TEENYBOPPER: 'teenybopper',
  THEATER: 'theater',
  TIME_AT_HOME: 'timeathome',
  TINYFORM: 'tinyform',
  TONGUE: 'tongue',
  TOOLS: 'tools',
  TRAVELER: 'traveler',
  TRUTH_OF_MY_CHEST: 'truthofmychest',
  TRUTH_ON_THE_TABLE: 'truthonthetable',
  TUBE: 'tube',
  TWO_AND_2: 'two&2',
  UFO_HISTORIANS: 'ufohistorians',
  UNDERSTANDABLE: 'understandable',
  UNSORTED: 'unsorted',
  USE_TECHNOLOGY: 'usetechnology',
  VALUE: 'value',
  VERTICAL_LEVEL: 'verticallevel',
  VICTIM_AM_I: 'victimami',
  VISSUAL: 'vissual',
  WEAR_AND_TEAR: 'wearandtead',
  WELL_WISHING: 'wellwishing',
  WETBASKET: 'wetbasket',
  WHO: 'who',
  WOOD_BOUND: 'woodbound',
  ZOMBIE: 'zombie',
}

export const SIGN_CATEGORY = {
  WORK: 'work',
  EAT: 'eat',
  SLEEP: 'sleep',
}

export const SIGN_COMPANY = {
  STANDARD: 'ikea',
  FRIEND: 'liddy',
  COMPETITOR: 'marcos',
}

export const HAND_VARIANTS = {
  TUMHAND: 'Tumhand',
  HOLD: 'hold',
  SPRET: 'spret',
  MEASURE: 'measure',
  KROK2: 'krok2',
  NYP: 'nyp',
  KLO: 'klo',
  R: 'r',
  KROK: 'krok',
  G: 'g',
  I: 'i',
  VINKEL: 'vinkel',
  N: 'n',
  V: 'v',
  E: 'e',
  D: 'd',
  STRAIGHTMEASURE: 'straightMeasure',
  J: 'j',
  TUPP: 'tupp',
  L: 'l',
  P: 'p',
  HAND4: 'hand4',
  T: 't',
  H: 'h',
  A: 'a',
  O: 'o',
  S: 's',
  TUMVINKEL: 'tumvinkel',
  B: 'b',
  FLYG: 'flyg',
}

export const ORIENTATION = {
  INWARD: 'inward',
  INWARDS: 'inwards',
  DOWNWARD: 'downward',
  FORWARD: 'forward',
  AGAIGNS: 'against',
  REAGAINST: 'reAgainst',
  UPPWARD: 'uppward',
  NULL: null,
  EMPTY: '',
}

export const POSITION = {
  SHOULDER: 'shoulder',
  CHEST: 'chest',
  HAND: 'hand',
  BACKHAND: 'backhand',
  FINGERS: 'fingers',
  PALM: 'palm',
  HEAD: 'head',
  STOMACHCHEST: 'stomach chest',
  FACE: 'face',
  SHOULDERCHEST: 'shoulder chest',
  CHESTHEAD: 'chest head',
  CHESTSHOULDER: 'chest shoulder',
  ARM: 'arm',
  NULL: 'null',
  NAN: 'NaN',
}

export const TOUCH_TYPE = {
  LINGER: 'bibehållen',
  MEDIAL: 'medial',
  ANGLE: 'vinkel',
  CROSS: 'kors',
  CROSSED: 'korsar',
  DRAG: 'drar',
  BRAIDING: 'flätande',
  CLOSED: 'sluten',
  HOOKED: 'hakas',
  HOOK: 'hakade',
  PINCH: 'nyper',
  NULL: null,
  EMPTY: '',
}

export const FACE_EXPRESSION = {
  PUH: 'puh',
  P: 'p',
  M: 'm',
  CHEEKS: '()',
  Y: 'y',
  F: 'f',
  A: 'a',
  Ä: 'ä',
  L: 'l',
  U: 'u',
  O: 'o',
  T: 't',
  S: 's',
  TH: 'th',
  PM: 'pm',
  PF: 'pf',
  PAFF: 'paff',
  PI: 'pi',
  PS: 'ps',
  PY: 'py',
  OPS: 'ops',
  OP: 'op',
  PU: 'pu',
  PÄ: 'pä',
  AP: 'ap',
  AS: 'as',
  ASAS: 'asas',
  ACHEAKS: 'a()',
  FA: 'fs',
  FSFS: 'fsfs',
  FT: 'ft',
  LS: 'ls',
  NULL: null,
  EMPTY: '',
}
